language: php

php:
  - 5.3
  - 5.4

before_script:
  - cp app/config/parameters.yml-dist app/config/parameters.yml
  - cp app/phpunit.xml.dist app/phpunit.xml
  - composer install
  
script: phpunit -c app --coverage-text

notifications:
  email:
    - info@arturgajewski.com
