imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: google.yml }
    - { resource: @CobaseAppBundle/Resources/config/config.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:         true
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        site_title: %site_title%
        allow_registration: %allow_registration%
        enable_google_analytics: %enable_google_analytics%

# Assetic Configuration
assetic:
    debug: %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        # jar: %kernel.root_dir%/java/compiler.jar
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.6.jar
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.6.jar
    bundles: [ "FOSCommentBundle" ]

fos_js_routing:
    routes_to_expose: [".*"]

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_all_services: false

fos_user:
    from_email:
        address:        %mailer_from%
        sender_name:    %mailer_name%
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Cobase\UserBundle\Entity\User

    profile:
        form:
            type: cobase_user_profile

    registration:
            form:
                type: cobase_user_registration
            confirmation:
                enabled: true

# Gravatar Configuration
ornicar_gravatar:
    rating: g
    size: 105
    default: mm

# Captcha
ewz_recaptcha:
    public_key:   6LcpWN4SAAAAAOmSwDeV365jlf-OAf3hJ2IvWLoq
    private_key:  6LcpWN4SAAAAANy1nu2Awuj1kEVLmbBbx1A6pItI
    secure:       false
    locale_key:   kernel.default_locale

# Url converter
liip_url_auto_converter:
    linkclass:
    target: _blank
    debugmode: false

eko_feed:
    feeds:
        post:
            title: 'Posts'
            description: 'Latest posts'
            link: 'cobase.featurice.com'
            encoding: 'utf-8'

fos_comment:
    db_driver: orm
    class:
        model:
            comment: Cobase\AppBundle\Entity\Comment
            thread: Cobase\AppBundle\Entity\Thread
    acl: true
    service:
        acl:
            thread:  fos_comment.acl.thread.roles
            comment: fos_comment.acl.comment.roles
            vote:    fos_comment.acl.vote.roles
        manager:
            thread:  fos_comment.manager.thread.acl
            comment: fos_comment.manager.comment.acl
            vote:    fos_comment.manager.vote.acl
    acl_roles:
        comment:
            create: ROLE_USER
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_ADMIN
            delete: ROLE_ADMIN
        thread:
            view: IS_AUTHENTICATED_ANONYMOUSLY
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_ADMIN
            delete: ROLE_ADMIN
        vote:
            create: ROLE_USER
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_ADMIN
            delete: ROLE_ADMIN