# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

CobaseAppBundle:
    resource: "@CobaseAppBundle/Resources/config/routing.yml"
    prefix:   /

_user_bundle:
    resource: "@CobaseUserBundle/Resources/config/routing.yml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /comment/api
    defaults: { _format: html }