CobaseAppBundle:
    resource: "@CobaseAppBundle/Resources/config/routing.yml"
    prefix:   /

_user_bundle:
    resource: "@CobaseUserBundle/Resources/config/routing.yml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"
    prefix:   /api

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
    prefix:   /api

cobase_api:
    resource: "@CobaseApiBundle/Resources/config/routing.yml"
    prefix:   /api

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal