jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        oauth_authorize:
            pattern: ^/api/oauth/v2/auth
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                check_path: /api/oauth/v2/auth_login_check
                login_path: /api/oauth/v2/auth_login
            logout: true
            anonymous: true

        oauth_token:
            pattern: ^/api/oauth/v2/token
            security: false

        api:
            pattern: ^/api
            fos_oauth: true
            stateless: true

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

    acl:
        connection: default

    access_control:
            - { path: ^/login$,        role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/register$,     role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/resetting$,    role: IS_AUTHENTICATED_ANONYMOUSLY }

            - { path: ^/profile,       role: ROLE_USER }

            - { path: ^/post/new,      role: ROLE_USER }
            - { path: ^/post/create,   role: ROLE_USER }
            - { path: ^/post/move,     role: ROLE_USER }
            - { path: ^/post/modify,   role: ROLE_USER }
            - { path: ^/post/delete,   role: ROLE_USER }

            - { path: ^/group/new,          role: ROLE_USER }
            - { path: ^/group/create,       role: ROLE_USER }
            - { path: ^/group/modify,       role: ROLE_USER }
            - { path: ^/group/delete,       role: ROLE_USER }
            - { path: ^/group/subscribe,    role: ROLE_USER }
            - { path: ^/group/unsubscribe,  role: ROLE_USER }

            # for the api
            - { path: ^/api/oauth/v2/auth_login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/api, role: IS_AUTHENTICATED_FULLY }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
