CobaseAppBundle_homepage:
    pattern:  /
    defaults: { _controller: CobaseAppBundle:Page:index }
    requirements:
        _method:  GET

CobaseAppBundle_group_subscribe:
    pattern:  /group/subscribe/{groupId}
    defaults: { _controller: CobaseAppBundle:Group:subscribe }

CobaseAppBundle_group_unsubscribe:
    pattern:  /group/unsubscribe/{groupId}
    defaults: { _controller: CobaseAppBundle:Group:unsubscribe }

CobaseAppBundle_group_notify:
    pattern:  /group/notify/{groupId}
    defaults: { _controller: CobaseAppBundle:Group:notify }

CobaseAppBundle_group_new:
    pattern:  /group/new
    defaults: { _controller: CobaseAppBundle:Group:new }

CobaseAppBundle_group_create:
    pattern:  /group/create
    defaults: { _controller: CobaseAppBundle:Group:create }

CobaseAppBundle_group_delete:
    pattern:  /group/delete
    defaults: { _controller: CobaseAppBundle:Group:delete }

CobaseAppBundle_group_view:
    pattern:  /group/{groupId}
    defaults: { _controller: CobaseAppBundle:Group:view }

CobaseAppBundle_group_modify:
    pattern:  /group/modify/{groupId}
    defaults: { _controller: CobaseAppBundle:Group:modify }

CobaseAppBundle_group_feed:
    pattern:  /group/{groupId}/rss
    defaults: { _controller: CobaseAppBundle:Group:feed }

CobaseAppBundle_group_search:
    pattern:  /search/group
    defaults: { _controller: CobaseAppBundle:Group:search }

CobaseAppBundle_all_groups:
    pattern:  /groups
    defaults: { _controller: CobaseAppBundle:Group:showAll }

CobaseAppBundle_all_groups_with_sorting:
    pattern:  /groups/{orderByType}/{orderType}
    defaults: { _controller: CobaseAppBundle:Group:showAll }

CobaseAppBundle_all_posts:
    pattern:  /posts
    defaults: { _controller: CobaseAppBundle:Post:showAll }

CobaseAppBundle_post_view:
    pattern:  /post/{groupId}/{postId}
    defaults: { _controller: CobaseAppBundle:Post:view }
    requirements:
        groupId:  "[a-zA-z0-9]+"
        postId:  \d+

CobaseAppBundle_post_feed:
    pattern:  /posts/rss
    defaults: { _controller: CobaseAppBundle:Post:feed }

CobaseAppBundle_all_posts_with_sorting:
    pattern:  /posts/{orderType}
    defaults: { _controller: CobaseAppBundle:Post:showAll }

CobaseAppBundle_post_modify:
    pattern:  /post/modify/{postId}
    defaults: { _controller: CobaseAppBundle:Post:modify }

CobaseAppBundle_post_move:
    pattern:  /post/move
    defaults: { _controller: CobaseAppBundle:Post:move }

CobaseAppBundle_post_delete:
    pattern:  /post/delete
    defaults: { _controller: CobaseAppBundle:Post:delete }

CobaseAppBundle_post_new:
    pattern:  /post/new
    defaults: { _controller: CobaseAppBundle:Post:new }

CobaseAppBundle_post_bookmarklet:
    pattern:  /javascripts/bookmarklet.js
    defaults: { _controller: CobaseAppBundle:Post:bookmarklet }

CobaseAppBundle_like_post:
    pattern:  /post/{postId}/like
    defaults: { _controller: CobaseAppBundle:Post:likePost }
    requirements:
        postId:  \d+

CobaseAppBundle_unlike_post:
    pattern:  /post/{postId}/unlike
    defaults: { _controller: CobaseAppBundle:Post:unlikePost }

CobaseAppBundle_get_post_likes:
    pattern:  /post/{postId}/likes
    defaults: { _controller: CobaseAppBundle:Post:getLikes }

CobaseAppBundle_users:
    pattern:  /users
    defaults: { _controller: CobaseAppBundle:User:showAll }

CobaseAppBundle_user_view:
    pattern:  /user/{username}
    defaults: { _controller: CobaseAppBundle:User:view }
