services:
    cobase_app.twig.extension:
        class: Cobase\AppBundle\Twig\Extensions\CobaseAppExtension
        tags:
            - { name: twig.extension }

    cobase_app.twig.like:
        class: Cobase\AppBundle\Twig\Extensions\Like
        arguments: ["@twig", "@cobase_app.service.user", "@cobase_app.service.post"]
        tags:
            - { name: twig.extension }

    cobase_app.twig.news:
            class: Cobase\AppBundle\Twig\Extensions\News
            arguments: ["@twig"]
            tags:
                - { name: twig.extension }

    aga_dateconverter.twig.extension:
        class: Aga\DateConverterBundle\Extension\DateConverterTwigExtension  
        tags:
            - { name: twig.extension }
           
    portal_user.registration.form.type:
        class: Cobase\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%, @translator]
        tags:
            - { name: form.type, alias: cobase_user_registration }

    cobase_user.profile.form.type:
            class: Cobase\UserBundle\Form\Type\ProfileFormType
            arguments: [%fos_user.model.user.class%]
            tags:
                - { name: form.type, alias: cobase_user_profile }

    cobase_app.service.group:
        class:     Cobase\AppBundle\Service\GroupService
        arguments: ["@doctrine.orm.entity_manager", "@cobase_app.repository.group", "@security.context"]

    cobase_app.repository.group:
        class:           Cobase\AppBundle\Entity\Group
        arguments:       [Cobase\AppBundle\Entity\Group]
        factory_service: doctrine.orm.entity_manager
        factory_method:  getRepository

    cobase_app.service.post:
            class:     Cobase\AppBundle\Service\PostService
            arguments: ["@doctrine.orm.entity_manager", "@cobase_app.repository.post", "@security.context", "@cobase_app.service.like"]

    cobase_app.repository.post:
            class:           Cobase\AppBundle\Entity\Post
            arguments:       [Cobase\AppBundle\Entity\Post]
            factory_service: doctrine.orm.entity_manager
            factory_method:  getRepository

    cobase_app.service.subscription:
            class:     Cobase\AppBundle\Service\SubscriptionService
            arguments: ["@doctrine.orm.entity_manager", "@cobase_app.repository.subscription", "@security.context"]

    cobase_app.repository.subscription:
            class:           Cobase\AppBundle\Entity\Subscription
            arguments:       [Cobase\AppBundle\Entity\Subscription]
            factory_service: doctrine.orm.entity_manager
            factory_method:  getRepository

    cobase_app.service.user:
                class:     Cobase\AppBundle\Service\UserService
                arguments: ["@doctrine.orm.entity_manager", "@cobase_app.repository.user", "@security.context"]

    cobase_app.repository.user:
                class:           Cobase\UserBundle\Entity\User
                arguments:       [Cobase\UserBundle\Entity\User]
                factory_service: doctrine.orm.entity_manager
                factory_method:  getRepository

    cobase_app.service.like:
        class:     Cobase\AppBundle\Service\LikeService
        arguments: ["@doctrine.orm.entity_manager", "@cobase_app.repository.like"]

    cobase_app.repository.like:
        class:           Cobase\AppBundle\Repository\Like
        arguments:       [Cobase\AppBundle\Entity\Like]
        factory_service: doctrine.orm.entity_manager
        factory_method:  getRepository

    gedmo.listener.softdeleteable:
        class: Gedmo\SoftDeleteable\SoftDeleteableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]