Cobase\AppBundle\Entity\Group:
    properties:
        title:
            - NotBlank: ~
            - MinLength: 5
            - MaxLength: 160
        description:
            - NotBlank: ~
            - MinLength: 5
            - MaxLength: 160
        tags:
            - NotBlank: ~
            - MaxLength: 160
            
Cobase\AppBundle\Entity\Post:
    properties:
        content:
            - NotBlank: ~
            - MinLength: 10
            - MaxLength: 1250