Cobase\AppBundle\Entity\Group:
    properties:
        title:
            - NotBlank: ~
            - Length:
                min: 5
                max: 160
        description:
            - NotBlank: ~
            - Length:
                min: 5
                max: 160
        tags:
            - NotBlank: ~
            - Length:
                max: 160
            
Cobase\AppBundle\Entity\Post:
    properties:
        content:
            - NotBlank: ~
            - Length:
                min: 10
                max: 1250