<?php

namespace Cobase\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Cobase\UserBundle\Entity\User;

/**
 * SubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriptionRepository extends EntityRepository
{
    /**
     * Find group subscriptions for a given user
     *
     * @param \Cobase\UserBundle\Entity\User $user
     * @return array
     */
    public function findAllForUser(User $user)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT s
             FROM Cobase\AppBundle\Entity\Subscription s 
             WHERE s.user = :user ORDER BY s.created ASC'
        )->setParameter('user', $user);

        return $query->getResult();
    }

    /**
     * Find posts related to groups user has subscribed to
     *
     * @param \Cobase\UserBundle\Entity\User $user
     * @return array
     */
    public function findAllSubscribedPostsForUser(User $user)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT p
             FROM Cobase\AppBundle\Entity\Subscription s,
             Cobase\AppBundle\Entity\Post p
             WHERE p.group = s.group
             and s.user = :user ORDER BY p.created DESC'
        )->setParameter('user', $user);

        return $query->getResult();
    }
}
