<?php

namespace Cobase\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Cobase\UserBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * Get latest users
     * 
     * @param null $limit
     * @return array
     */
    public function getLatestUsers($limit = null)
    {
        $qb = $this->createQueryBuilder('b')
            ->select('b')
            ->where('b.enabled = 1')
            ->addOrderBy('b.id', 'DESC');
            
        if ($limit !== null) {
            $qb->setMaxResults($limit);
        }

        return $qb->getQuery()
            ->getResult();
    }

    /**
     * Find groups created by a user
     *
     * @param \Cobase\UserBundle\Entity\User $user
     * @return array
     */
    public function findAllGroupsByUser(User $user)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT g
             FROM Cobase\AppBundle\Entity\Group g 
             WHERE g.user = :user ORDER BY g.created ASC'
        )->setParameter('user', $user);

        return $query->getResult();
    }

    /**
     * Find posts created by a user
     *
     * @param \Cobase\UserBundle\Entity\User $user
     * @return array
     */
    public function findAllPostsByUser(User $user)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT p
             FROM Cobase\AppBundle\Entity\Post p 
             WHERE p.user = :user ORDER BY p.created ASC'
        )->setParameter('user', $user);

        return $query->getResult();
    }
}
