<?php

namespace Cobase\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Cobase\UserBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * Get latest users
     * 
     * @param null $limit
     * @return array
     */
    public function getLatestUsers($limit = null)
    {
        $qb = $this->createQueryBuilder('b')
            ->select('b')
            ->addOrderBy('b.id', 'DESC');
            
        if ($limit !== null) {
            $qb->setMaxResults($limit);
        }

        return $qb->getQuery()
            ->getResult();
    }
}
